"""AGRVelocitySmootherBase — auto-generated from SysML v2 model. DO NOT EDIT.

This base class is REWRITTEN on every pipeline run (generation-gap pattern):
all architectural wiring lives here. Put demo/application logic in the sibling
a_g_r_velocity_smoother_node.py, which is generated once and never overwritten.

Node: velocity_smoother (/safety)
Archetype: VelocityFilter
Generated by: ros2-sysmlv2 bridge pipeline
Mode: FULLY-WIRED — all endpoints seeded with default data for topology verification.
"""
from rclpy.lifecycle import LifecycleNode, TransitionCallbackReturn, LifecycleState
from geometry_msgs.msg import Twist
from rclpy.qos import qos_profile_system_default


class AGRVelocitySmootherBase(LifecycleNode):
    """Lifecycle wiring for velocity_smoother — endpoints, parameters, transitions.

    Override the on_*_hook() methods and handle_*() message handlers in the
    derived class; do not override the lifecycle transition methods themselves.
    """

    def __init__(self, node_name: str = 'velocity_smoother'):
        super().__init__(node_name=node_name)
        self.get_logger().info('AGRVelocitySmoother created (unconfigured)')

    def on_configure(self, state: LifecycleState) -> TransitionCallbackReturn:
        """Configure: create publishers, subscribers, and declare parameters."""
        self.get_logger().info('Configuring...')

        # Publisher: cmdVelOut → /cmd_vel_smooth
        self.cmdVelOut = self.create_lifecycle_publisher(
            Twist,
            '/cmd_vel_smooth',
            qos_profile_system_default)

        # Subscriber: cmdVelIn ← /cmd_vel
        self.cmdVelIn = self.create_subscription(
            Twist,
            '/cmd_vel',
            self._cmdVelIn_callback,
            10)

        self.on_configure_hook()
        return TransitionCallbackReturn.SUCCESS

    def on_activate(self, state: LifecycleState) -> TransitionCallbackReturn:
        """Activate: start processing."""
        self.get_logger().info('Activating...')

        # ── Fully-wired mode: publish default messages for topology verification ──
        self._cmdVelOut_timer = self.create_timer(
            1.0, self._cmdVelOut_wired_publish)
        self.on_activate_hook()
        return super().on_activate(state)

    def on_deactivate(self, state: LifecycleState) -> TransitionCallbackReturn:
        """Deactivate: pause processing."""
        self.get_logger().info('Deactivating...')
        self._cmdVelOut_timer.cancel()
        self.on_deactivate_hook()
        return super().on_deactivate(state)

    def on_cleanup(self, state: LifecycleState) -> TransitionCallbackReturn:
        """Cleanup: release resources."""
        self.get_logger().info('Cleaning up...')
        return TransitionCallbackReturn.SUCCESS

    def on_shutdown(self, state: LifecycleState) -> TransitionCallbackReturn:
        """Shutdown: final cleanup."""
        self.get_logger().info('Shutting down...')
        return TransitionCallbackReturn.SUCCESS

    # ── Hooks for the derived class ──────────────────────────────────

    def on_configure_hook(self) -> None:
        """Called at the end of on_configure. Override in the derived class."""

    def on_activate_hook(self) -> None:
        """Called during on_activate. Override in the derived class."""

    def on_deactivate_hook(self) -> None:
        """Called during on_deactivate. Override in the derived class."""

    def handle_cmdVelIn(self, msg) -> None:
        """Handler for /cmd_vel (Twist). Override in the derived class."""

    # ── Internal dispatch (owned by the base class) ──────────────────

    def _cmdVelIn_callback(self, msg):
        self.get_logger().debug(f'[wired] Received on /cmd_vel')
        self.handle_cmdVelIn(msg)

    def _cmdVelOut_wired_publish(self):
        """Wired-mode publisher for /cmd_vel_smooth — emits default Twist."""
        msg = Twist()
        self.cmdVelOut.publish(msg)
