"""MissionCoordinatorBase — auto-generated from SysML v2 model. DO NOT EDIT.

This base class is REWRITTEN on every pipeline run (generation-gap pattern):
all architectural wiring lives here. Put demo/application logic in the sibling
mission_coordinator_node.py, which is generated once and never overwritten.

Node: mission_coordinator (/)
Archetype: BehaviorCoordinator
Generated by: ros2-sysmlv2 bridge pipeline
Mode: FULLY-WIRED — all endpoints seeded with default data for topology verification.
"""
from rclpy.lifecycle import LifecycleNode, TransitionCallbackReturn, LifecycleState
from nav_msgs.msg import Path


class MissionCoordinatorBase(LifecycleNode):
    """Lifecycle wiring for mission_coordinator — endpoints, parameters, transitions.

    Override the on_*_hook() methods and handle_*() message handlers in the
    derived class; do not override the lifecycle transition methods themselves.
    """

    def __init__(self, node_name: str = 'mission_coordinator'):
        super().__init__(node_name=node_name)
        self.get_logger().info('MissionCoordinator created (unconfigured)')

    def on_configure(self, state: LifecycleState) -> TransitionCallbackReturn:
        """Configure: create publishers, subscribers, and declare parameters."""
        self.get_logger().info('Configuring...')

        # Publisher: statusPub → /mission_status
        self.statusPub = self.create_lifecycle_publisher(
            Path,
            '/mission_status',
            10)

        self.on_configure_hook()
        return TransitionCallbackReturn.SUCCESS

    def on_activate(self, state: LifecycleState) -> TransitionCallbackReturn:
        """Activate: start processing."""
        self.get_logger().info('Activating...')

        # ── Fully-wired mode: publish default messages for topology verification ──
        self._statusPub_timer = self.create_timer(
            1.0, self._statusPub_wired_publish)
        self.on_activate_hook()
        return super().on_activate(state)

    def on_deactivate(self, state: LifecycleState) -> TransitionCallbackReturn:
        """Deactivate: pause processing."""
        self.get_logger().info('Deactivating...')
        self._statusPub_timer.cancel()
        self.on_deactivate_hook()
        return super().on_deactivate(state)

    def on_cleanup(self, state: LifecycleState) -> TransitionCallbackReturn:
        """Cleanup: release resources."""
        self.get_logger().info('Cleaning up...')
        return TransitionCallbackReturn.SUCCESS

    def on_shutdown(self, state: LifecycleState) -> TransitionCallbackReturn:
        """Shutdown: final cleanup."""
        self.get_logger().info('Shutting down...')
        return TransitionCallbackReturn.SUCCESS

    # ── Hooks for the derived class ──────────────────────────────────

    def on_configure_hook(self) -> None:
        """Called at the end of on_configure. Override in the derived class."""

    def on_activate_hook(self) -> None:
        """Called during on_activate. Override in the derived class."""

    def on_deactivate_hook(self) -> None:
        """Called during on_deactivate. Override in the derived class."""

    # ── Internal dispatch (owned by the base class) ──────────────────

    def _statusPub_wired_publish(self):
        """Wired-mode publisher for /mission_status — emits default Path."""
        msg = Path()
        self.statusPub.publish(msg)
