"""ObstacleDetectorBase — auto-generated from SysML v2 model. DO NOT EDIT.

This base class is REWRITTEN on every pipeline run (generation-gap pattern):
all architectural wiring lives here. Put demo/application logic in the sibling
obstacle_detector_node.py, which is generated once and never overwritten.

Node: obstacle_detector (/perception)
Archetype: PerceptionPipeline
Generated by: ros2-sysmlv2 bridge pipeline
Mode: FULLY-WIRED — all endpoints seeded with default data for topology verification.
"""
from rclpy.lifecycle import LifecycleNode, TransitionCallbackReturn, LifecycleState
from rclpy.qos import qos_profile_sensor_data
from sensor_msgs.msg import Image
from sensor_msgs.msg import LaserScan
from sensor_msgs.msg import PointCloud2


class ObstacleDetectorBase(LifecycleNode):
    """Lifecycle wiring for obstacle_detector — endpoints, parameters, transitions.

    Override the on_*_hook() methods and handle_*() message handlers in the
    derived class; do not override the lifecycle transition methods themselves.
    """

    def __init__(self, node_name: str = 'obstacle_detector'):
        super().__init__(node_name=node_name)
        self.get_logger().info('ObstacleDetector created (unconfigured)')

    def on_configure(self, state: LifecycleState) -> TransitionCallbackReturn:
        """Configure: create publishers, subscribers, and declare parameters."""
        self.get_logger().info('Configuring...')

        # Publisher: processedPub → /detections
        self.processedPub = self.create_lifecycle_publisher(
            PointCloud2,
            '/detections',
            10)

        # Subscriber: rawSub ← /scan
        self.rawSub = self.create_subscription(
            LaserScan,
            '/scan',
            self._rawSub_callback,
            qos_profile_sensor_data)

        # Subscriber: cameraSub ← /camera/image
        self.cameraSub = self.create_subscription(
            Image,
            '/camera/image',
            self._cameraSub_callback,
            qos_profile_sensor_data)

        self.on_configure_hook()
        return TransitionCallbackReturn.SUCCESS

    def on_activate(self, state: LifecycleState) -> TransitionCallbackReturn:
        """Activate: start processing."""
        self.get_logger().info('Activating...')

        # ── Fully-wired mode: publish default messages for topology verification ──
        self._processedPub_timer = self.create_timer(
            1.0, self._processedPub_wired_publish)
        self.on_activate_hook()
        return super().on_activate(state)

    def on_deactivate(self, state: LifecycleState) -> TransitionCallbackReturn:
        """Deactivate: pause processing."""
        self.get_logger().info('Deactivating...')
        self._processedPub_timer.cancel()
        self.on_deactivate_hook()
        return super().on_deactivate(state)

    def on_cleanup(self, state: LifecycleState) -> TransitionCallbackReturn:
        """Cleanup: release resources."""
        self.get_logger().info('Cleaning up...')
        return TransitionCallbackReturn.SUCCESS

    def on_shutdown(self, state: LifecycleState) -> TransitionCallbackReturn:
        """Shutdown: final cleanup."""
        self.get_logger().info('Shutting down...')
        return TransitionCallbackReturn.SUCCESS

    # ── Hooks for the derived class ──────────────────────────────────

    def on_configure_hook(self) -> None:
        """Called at the end of on_configure. Override in the derived class."""

    def on_activate_hook(self) -> None:
        """Called during on_activate. Override in the derived class."""

    def on_deactivate_hook(self) -> None:
        """Called during on_deactivate. Override in the derived class."""

    def handle_rawSub(self, msg) -> None:
        """Handler for /scan (LaserScan). Override in the derived class."""

    def handle_cameraSub(self, msg) -> None:
        """Handler for /camera/image (Image). Override in the derived class."""

    # ── Internal dispatch (owned by the base class) ──────────────────

    def _rawSub_callback(self, msg):
        self.get_logger().debug(f'[wired] Received on /scan')
        self.handle_rawSub(msg)

    def _cameraSub_callback(self, msg):
        self.get_logger().debug(f'[wired] Received on /camera/image')
        self.handle_cameraSub(msg)

    def _processedPub_wired_publish(self):
        """Wired-mode publisher for /detections — emits default PointCloud2."""
        msg = PointCloud2()
        self.processedPub.publish(msg)
