// CollisionGuardBase — auto-generated from SysML v2 model. DO NOT EDIT.
//
// This base class is REWRITTEN on every pipeline run (generation-gap pattern):
// all architectural wiring lives here. Put demo/application logic in
// src/collision_guard_node.cpp, which is generated once and never overwritten.
//
// Node: collision_guard (/safety)
// Archetype: VelocityFilter
// Generated by: ros2-sysmlv2 bridge pipeline
// Mode: FULLY-WIRED — all endpoints seeded with default data for topology verification.
#pragma once

#include <string>

#include <rclcpp/rclcpp.hpp>
#include <rclcpp_lifecycle/lifecycle_node.hpp>
#include <geometry_msgs/msg/twist.hpp>
#include <sensor_msgs/msg/laser_scan.hpp>

class CollisionGuardBase : public rclcpp_lifecycle::LifecycleNode
{
public:
  using CallbackReturn =
    rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;

  explicit CollisionGuardBase(
    const rclcpp::NodeOptions & options = rclcpp::NodeOptions());

  // Lifecycle transitions — owned by the base class; do not override.
  CallbackReturn on_configure(const rclcpp_lifecycle::State & state) override;
  CallbackReturn on_activate(const rclcpp_lifecycle::State & state) override;
  CallbackReturn on_deactivate(const rclcpp_lifecycle::State & state) override;
  CallbackReturn on_cleanup(const rclcpp_lifecycle::State & state) override;
  CallbackReturn on_shutdown(const rclcpp_lifecycle::State & state) override;

protected:
  // ── Hooks for the derived class ──────────────────────────────────
  virtual void on_configure_hook() {}
  virtual void on_activate_hook() {}
  virtual void on_deactivate_hook() {}
  // Handler for /cmd_vel_smooth — override in the derived class.
  virtual void handle_cmdVelIn(const geometry_msgs::msg::Twist & msg) { (void)msg; }
  // Handler for /scan — override in the derived class.
  virtual void handle_scanSub(const sensor_msgs::msg::LaserScan & msg) { (void)msg; }

  // ── Endpoints (protected so derived logic can publish) ───────────
  rclcpp_lifecycle::LifecyclePublisher<geometry_msgs::msg::Twist>::SharedPtr cmdVelOut_;
  rclcpp::Subscription<geometry_msgs::msg::Twist>::SharedPtr cmdVelIn_;
  rclcpp::Subscription<sensor_msgs::msg::LaserScan>::SharedPtr scanSub_;

private:
  void cmdVelIn_callback(const geometry_msgs::msg::Twist & msg);
  void scanSub_callback(const sensor_msgs::msg::LaserScan & msg);
  void cmdVelOut_wired_publish();
  rclcpp::TimerBase::SharedPtr cmdVelOut_timer_;
};
