// PathPlannerBase — auto-generated from SysML v2 model. DO NOT EDIT.
//
// This base class is REWRITTEN on every pipeline run (generation-gap pattern):
// all architectural wiring lives here. Put demo/application logic in
// src/path_planner_node.cpp, which is generated once and never overwritten.
//
// Node: path_planner (/planning)
// Archetype: Planner
// Generated by: ros2-sysmlv2 bridge pipeline
// Mode: FULLY-WIRED — all endpoints seeded with default data for topology verification.
#pragma once

#include <string>

#include <rclcpp/rclcpp.hpp>
#include <rclcpp_lifecycle/lifecycle_node.hpp>
#include <nav_msgs/msg/occupancy_grid.hpp>
#include <nav_msgs/msg/path.hpp>
#include <sensor_msgs/msg/point_cloud2.hpp>

class PathPlannerBase : public rclcpp_lifecycle::LifecycleNode
{
public:
  using CallbackReturn =
    rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;

  explicit PathPlannerBase(
    const rclcpp::NodeOptions & options = rclcpp::NodeOptions());

  // Lifecycle transitions — owned by the base class; do not override.
  CallbackReturn on_configure(const rclcpp_lifecycle::State & state) override;
  CallbackReturn on_activate(const rclcpp_lifecycle::State & state) override;
  CallbackReturn on_deactivate(const rclcpp_lifecycle::State & state) override;
  CallbackReturn on_cleanup(const rclcpp_lifecycle::State & state) override;
  CallbackReturn on_shutdown(const rclcpp_lifecycle::State & state) override;

protected:
  // ── Hooks for the derived class ──────────────────────────────────
  virtual void on_configure_hook() {}
  virtual void on_activate_hook() {}
  virtual void on_deactivate_hook() {}
  // Handler for /map — override in the derived class.
  virtual void handle_mapSub(const nav_msgs::msg::OccupancyGrid & msg) { (void)msg; }
  // Handler for /detections — override in the derived class.
  virtual void handle_detectionsSub(const sensor_msgs::msg::PointCloud2 & msg) { (void)msg; }

  // ── Endpoints (protected so derived logic can publish) ───────────
  rclcpp_lifecycle::LifecyclePublisher<nav_msgs::msg::Path>::SharedPtr planPub_;
  rclcpp::Subscription<nav_msgs::msg::OccupancyGrid>::SharedPtr mapSub_;
  rclcpp::Subscription<sensor_msgs::msg::PointCloud2>::SharedPtr detectionsSub_;

private:
  void mapSub_callback(const nav_msgs::msg::OccupancyGrid & msg);
  void detectionsSub_callback(const sensor_msgs::msg::PointCloud2 & msg);
  void planPub_wired_publish();
  rclcpp::TimerBase::SharedPtr planPub_timer_;
};
