// StaticMapServerBase — auto-generated from SysML v2 model. DO NOT EDIT.
//
// This base class is REWRITTEN on every pipeline run (generation-gap pattern):
// all architectural wiring lives here. Put demo/application logic in
// src/static_map_server_node.cpp, which is generated once and never overwritten.
//
// Node: map_server (/)
// Archetype: MapProvider
// Generated by: ros2-sysmlv2 bridge pipeline
// Mode: FULLY-WIRED — all endpoints seeded with default data for topology verification.
#pragma once

#include <string>

#include <rclcpp/rclcpp.hpp>
#include <rclcpp_lifecycle/lifecycle_node.hpp>
#include <nav_msgs/msg/occupancy_grid.hpp>

class StaticMapServerBase : public rclcpp_lifecycle::LifecycleNode
{
public:
  using CallbackReturn =
    rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;

  explicit StaticMapServerBase(
    const rclcpp::NodeOptions & options = rclcpp::NodeOptions());

  // Lifecycle transitions — owned by the base class; do not override.
  CallbackReturn on_configure(const rclcpp_lifecycle::State & state) override;
  CallbackReturn on_activate(const rclcpp_lifecycle::State & state) override;
  CallbackReturn on_deactivate(const rclcpp_lifecycle::State & state) override;
  CallbackReturn on_cleanup(const rclcpp_lifecycle::State & state) override;
  CallbackReturn on_shutdown(const rclcpp_lifecycle::State & state) override;

protected:
  // ── Hooks for the derived class ──────────────────────────────────
  virtual void on_configure_hook() {}
  virtual void on_activate_hook() {}
  virtual void on_deactivate_hook() {}

  // ── Endpoints (protected so derived logic can publish) ───────────
  rclcpp_lifecycle::LifecyclePublisher<nav_msgs::msg::OccupancyGrid>::SharedPtr mapPub_;

private:
  void mapPub_wired_publish();
  rclcpp::TimerBase::SharedPtr mapPub_timer_;
};
