// DepthCameraDriverBase — auto-generated from SysML v2 model. DO NOT EDIT.
//
// This base class is REWRITTEN on every pipeline run (generation-gap pattern):
// all architectural wiring lives here. Put demo/application logic in
// src/depth_camera_driver_node.cpp, which is generated once and never overwritten.
//
// Node: depth_camera (/sensors)
// Archetype: SensorDriver
// Generated by: ros2-sysmlv2 bridge pipeline
// Mode: FULLY-WIRED — all endpoints seeded with default data for topology verification.
#pragma once

#include <string>

#include <rclcpp/rclcpp.hpp>
#include <rclcpp_lifecycle/lifecycle_node.hpp>
#include <sensor_msgs/msg/camera_info.hpp>
#include <sensor_msgs/msg/image.hpp>

class DepthCameraDriverBase : public rclcpp_lifecycle::LifecycleNode
{
public:
  using CallbackReturn =
    rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;

  explicit DepthCameraDriverBase(
    const rclcpp::NodeOptions & options = rclcpp::NodeOptions());

  // Lifecycle transitions — owned by the base class; do not override.
  CallbackReturn on_configure(const rclcpp_lifecycle::State & state) override;
  CallbackReturn on_activate(const rclcpp_lifecycle::State & state) override;
  CallbackReturn on_deactivate(const rclcpp_lifecycle::State & state) override;
  CallbackReturn on_cleanup(const rclcpp_lifecycle::State & state) override;
  CallbackReturn on_shutdown(const rclcpp_lifecycle::State & state) override;

protected:
  // ── Hooks for the derived class ──────────────────────────────────
  virtual void on_configure_hook() {}
  virtual void on_activate_hook() {}
  virtual void on_deactivate_hook() {}

  // ── Endpoints (protected so derived logic can publish) ───────────
  rclcpp_lifecycle::LifecyclePublisher<sensor_msgs::msg::Image>::SharedPtr sensorPub_;
  rclcpp_lifecycle::LifecyclePublisher<sensor_msgs::msg::CameraInfo>::SharedPtr cameraInfoPub_;

private:
  void sensorPub_wired_publish();
  rclcpp::TimerBase::SharedPtr sensorPub_timer_;
  void cameraInfoPub_wired_publish();
  rclcpp::TimerBase::SharedPtr cameraInfoPub_timer_;
};
