// Nav2EKFLocalizerBase — auto-generated from SysML v2 model. DO NOT EDIT.
//
// This base class is REWRITTEN on every pipeline run (generation-gap pattern):
// all architectural wiring lives here. Put demo/application logic in
// src/nav2_e_k_f_localizer_node.cpp, which is generated once and never overwritten.
//
// Node: ekf_localizer (/estimation)
// Archetype: Estimator
// Generated by: ros2-sysmlv2 bridge pipeline
// Mode: FULLY-WIRED — all endpoints seeded with default data for topology verification.
#pragma once

#include <string>

#include <rclcpp/rclcpp.hpp>
#include <rclcpp_lifecycle/lifecycle_node.hpp>
#include <geometry_msgs/msg/pose_with_covariance_stamped.hpp>
#include <nav_msgs/msg/odometry.hpp>
#include <sensor_msgs/msg/imu.hpp>
#include <sensor_msgs/msg/laser_scan.hpp>

class Nav2EKFLocalizerBase : public rclcpp_lifecycle::LifecycleNode
{
public:
  using CallbackReturn =
    rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;

  explicit Nav2EKFLocalizerBase(
    const rclcpp::NodeOptions & options = rclcpp::NodeOptions());

  // Lifecycle transitions — owned by the base class; do not override.
  CallbackReturn on_configure(const rclcpp_lifecycle::State & state) override;
  CallbackReturn on_activate(const rclcpp_lifecycle::State & state) override;
  CallbackReturn on_deactivate(const rclcpp_lifecycle::State & state) override;
  CallbackReturn on_cleanup(const rclcpp_lifecycle::State & state) override;
  CallbackReturn on_shutdown(const rclcpp_lifecycle::State & state) override;

protected:
  // ── Hooks for the derived class ──────────────────────────────────
  virtual void on_configure_hook() {}
  virtual void on_activate_hook() {}
  virtual void on_deactivate_hook() {}
  // Handler for /imu/data — override in the derived class.
  virtual void handle_sensorSub(const sensor_msgs::msg::Imu & msg) { (void)msg; }
  // Handler for /scan — override in the derived class.
  virtual void handle_scanSub(const sensor_msgs::msg::LaserScan & msg) { (void)msg; }

  // ── Endpoints (protected so derived logic can publish) ───────────
  rclcpp_lifecycle::LifecyclePublisher<nav_msgs::msg::Odometry>::SharedPtr posePub_;
  rclcpp_lifecycle::LifecyclePublisher<geometry_msgs::msg::PoseWithCovarianceStamped>::SharedPtr poseCovPub_;
  rclcpp::Subscription<sensor_msgs::msg::Imu>::SharedPtr sensorSub_;
  rclcpp::Subscription<sensor_msgs::msg::LaserScan>::SharedPtr scanSub_;

private:
  void sensorSub_callback(const sensor_msgs::msg::Imu & msg);
  void scanSub_callback(const sensor_msgs::msg::LaserScan & msg);
  void posePub_wired_publish();
  rclcpp::TimerBase::SharedPtr posePub_timer_;
  void poseCovPub_wired_publish();
  rclcpp::TimerBase::SharedPtr poseCovPub_timer_;
};
